export const projectsContentList = [
  {
    id: 1001,
    projectName: "Тест DOD",
    status: "New",
    partOpen: "12",
    partClosed: 13,
    date: "15.01.2025",
    author: "admin admin",
  },
  {
    id: 1002,
    projectName: "Название 123",
    status: "New",
    partOpen: "12",
    partClosed: 13,
    date: "16.01.2025",
    author: "admin admin",
  },
  {
    id: 1003,
    projectName: "Test tets",
    status: "Closed",
    partOpen: "12",
    partClosed: 13,
    date: "19.01.2025",
    author: "admin admin",
  },
  {
    id: 1004,
    projectName: "New test",
    status: "Closed",
    partOpen: "12",
    partClosed: 13,
    date: "23.01.2025",
    author: "admin admin",
  },
  {
    id: 1005,
    projectName: "DOD DOD 222",
    status: "New",
    partOpen: "12",
    partClosed: 13,
    date: "25.01.2025",
    author: "admin admin",
  },
];

export const projectsContentListTetrad = [
  {
    id: 1006,
    projectName: "Тест тетрадь",
    status: "New",
    partOpen: "12",
    partClosed: 13,
    date: "16.01.2025",
    author: "admin admin",
  },
  {
    id: 1007,
    projectName: "Tetrad Coffee",
    status: "New",
    partOpen: "12",
    partClosed: 13,
    date: "17.01.2025",
    author: "admin admin",
  },
  {
    id: 1008,
    projectName: "New test 45645",
    status: "Closed",
    partOpen: "12",
    partClosed: 13,
    date: "20.01.2025",
    author: "admin admin",
  },
];
