FROM node:20-alpine as dependencies
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --frozen-lockfile

FROM node:20-alpine as builder
ARG NEXT_PUBLIC_FRONTEND_URL
ARG SKIP_BUILD_STATIC_GENERATION
WORKDIR /app
ENV NEXT_PUBLIC_FRONTEND_URL=https://site.spaaace.io
ENV SKIP_BUILD_STATIC_GENERATION=false
COPY . .
COPY --from=dependencies /app/node_modules ./node_modules
RUN env
RUN npm run build


FROM node:20-alpine as runner
WORKDIR /app
# ENV NODE_ENV production

COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/next.config.js ./next.config.js

EXPOSE 3000
CMD ["npm", "start"]
